name: gofumpt

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        set-safe-directory: '*'
        ref: ${{ github.head_ref }}
        fetch-depth: 0
    - name: Set ownership
      run: chown -R $(id -u):$(id -g) $PWD
    - name: auto-gofmt
      uses: iamnotaturtle/auto-gofmt@master
